on:
  push:
    branches:
      - master
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 generate-readme.py
      - uses: stefanzweifel/git-auto-commit-action@v4
